"""Output formatters for pull request descriptions and issue comments.

Generates structured Markdown for pull request descriptions, and Jira
wiki markup for comments. Both formatters work from structured data
(file changes, commit info) rather than from free-form agent output,
so the result is consistent across runs and across agents.
"""

from __future__ import annotations

from datetime import datetime

from yokai.core.models import (
    AgentResult,
    CommitInfo,
    FileChange,
    Story,
)


def _shorten(path: str, max_len: int = 60) -> str:
    if len(path) <= max_len:
        return path
    return path.split("/")[-1]


def build_pr_description(
    story: Story,
    story_url: str,
    branch_name: str,
    target_branch: str,
    commit: CommitInfo,
    changed_files: list[FileChange],
    timestamp: datetime | None = None,
) -> str:
    ts = (timestamp or datetime.now()).strftime("%Y-%m-%d %H:%M")

    src_files = [f for f in changed_files if not f.is_test]
    test_files = [f for f in changed_files if f.is_test]
    total_added = sum(f.added for f in changed_files)
    total_removed = sum(f.removed for f in changed_files)

    lines: list[str] = []
    lines.append("## Generated by yokai")
    lines.append("")
    lines.append(f"**Story:** [{story.key}]({story_url}) - {story.title}")
    lines.append(f"**Branch:** `{branch_name}` -> `{target_branch}`")
    lines.append(f"**Commit:** `{commit.short_sha}`")
    lines.append(f"**Generated:** {ts}")
    lines.append("")
    lines.append(
        f"### Changed files ({len(changed_files)} total, "
        f"+{total_added} -{total_removed})"
    )
    lines.append("")

    if src_files:
        lines.append(f"**Source ({len(src_files)}):**")
        lines.append("")
        lines.append("| File | Changes |")
        lines.append("|---|---|")
        for f in src_files:
            lines.append(f"| `{_shorten(f.path)}` | +{f.added} -{f.removed} |")
        lines.append("")

    if test_files:
        lines.append(f"**Tests ({len(test_files)}):**")
        lines.append("")
        lines.append("| File | Changes |")
        lines.append("|---|---|")
        for f in test_files:
            lines.append(f"| `{_shorten(f.path)}` | +{f.added} -{f.removed} |")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("Requires human review before merge.")
    lines.append("")
    lines.append(
        "Detailed implementation notes from the coding agent are available "
        f"as a comment on [{story.key}]({story_url})."
    )
    return "\n".join(lines)


def build_jira_short_comment(
    pr_url: str,
    branch_name: str,
    changed_files: list[FileChange],
) -> str:
    src_count = sum(1 for f in changed_files if not f.is_test)
    test_count = sum(1 for f in changed_files if f.is_test)
    total_added = sum(f.added for f in changed_files)
    total_removed = sum(f.removed for f in changed_files)

    lines = [
        "*Pull request generated by yokai*",
        "",
        f"*PR link:* {pr_url}",
        f"*Branch:* {{{{{branch_name}}}}}",
        f"*Files changed:* {len(changed_files)} ({src_count} source, {test_count} tests)",
        f"*Diff size:* +{total_added} / -{total_removed}",
        "",
        "Pull request is ready for review.",
        "See next comment for the detailed agent output.",
    ]
    return "\n".join(lines)


def build_jira_detailed_comment(agent_result: AgentResult) -> str:
    lines = [
        "h3. Agent execution details",
        "",
        "{panel:title=Coding agent output|borderStyle=solid|borderColor=#ccc"
        "|titleBGColor=#f4f5f7|bgColor=#ffffff}",
        "",
        "{noformat}",
        agent_result.output.strip(),
        "{noformat}",
        "",
        "{panel}",
    ]
    return "\n".join(lines)
