"""Output formatters for pull request descriptions and issue comments.

Generates structured Markdown for pull request descriptions, and Jira
wiki markup for comments. Both formatters work from structured data
(file changes, commit info) rather than from free-form agent output,
so the result is consistent across runs and across agents.
"""

from __future__ import annotations

from datetime import datetime

from yokai.core.models import (
    AgentResult,
    CommitInfo,
    FileChange,
    Story,
)


def _shorten(path: str, max_len: int = 60) -> str:
    if len(path) <= max_len:
        return path
    return path.split("/")[-1]


def build_pr_description(
    story: Story,
    story_url: str,
    branch_name: str,
    target_branch: str,
    commit: CommitInfo,
    changed_files: list[FileChange],
    timestamp: datetime | None = None,
) -> str:
    ts = (timestamp or datetime.now()).strftime("%Y-%m-%d %H:%M")

    src_files = [f for f in changed_files if not f.is_test]
    test_files = [f for f in changed_files if f.is_test]
    total_added = sum(f.added for f in changed_files)
    total_removed = sum(f.removed for f in changed_files)

    lines: list[str] = []
    lines.append("## Generated by yokai")
    lines.append("")
    lines.append(f"**Story:** [{story.key}]({story_url}) - {story.title}")
    lines.append(f"**Branch:** `{branch_name}` -> `{target_branch}`")
    lines.append(f"**Commit:** `{commit.short_sha}`")
    lines.append(f"**Generated:** {ts}")
    lines.append("")
    lines.append(
        f"### Changed files ({len(changed_files)} total, "
        f"+{total_added} -{total_removed})"
    )
    lines.append("")

    if src_files:
        lines.append(f"**Source ({len(src_files)}):**")
        lines.append("")
        lines.append("| File | Changes |")
        lines.append("|---|---|")
        for f in src_files:
            lines.append(f"| `{_shorten(f.path)}` | +{f.added} -{f.removed} |")
        lines.append("")

    if test_files:
        lines.append(f"**Tests ({len(test_files)}):**")
        lines.append("")
        lines.append("| File | Changes |")
        lines.append("|---|---|")
        for f in test_files:
            lines.append(f"| `{_shorten(f.path)}` | +{f.added} -{f.removed} |")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("Requires human review before merge.")
    lines.append("")
    lines.append(
        "Detailed implementation notes from the coding agent are available "
        f"as a comment on [{story.key}]({story_url})."
    )
    return "\n".join(lines)


def build_jira_short_comment(
    pr_url: str,
    branch_name: str,
    changed_files: list[FileChange],
) -> str:
    src_count = sum(1 for f in changed_files if not f.is_test)
    test_count = sum(1 for f in changed_files if f.is_test)
    total_added = sum(f.added for f in changed_files)
    total_removed = sum(f.removed for f in changed_files)

    lines = [
        "*Pull request generated by yokai*",
        "",
        f"*PR link:* {pr_url}",
        f"*Branch:* {{{{{branch_name}}}}}",
        f"*Files changed:* {len(changed_files)} ({src_count} source, {test_count} tests)",
        f"*Diff size:* +{total_added} / -{total_removed}",
        "",
        "Pull request is ready for review.",
        "See next comment for the detailed agent output.",
    ]
    return "\n".join(lines)


def markdown_to_jira_wiki(text: str) -> str:
    """Convert Markdown output (from Claude Code) to Jira wiki markup.

    Handles the most common constructs that appear in agent summaries:
    headers, bold, inline code, code blocks, and tables. Does not
    attempt to be a full Markdown parser - just enough for structured
    agent output to render correctly in Jira Data Center.
    """
    import re

    lines = text.split("\n")
    result: list[str] = []
    in_code_block = False
    code_block_lines: list[str] = []

    for line in lines:
        # Fenced code blocks: ```lang ... ```
        if line.strip().startswith("```"):
            if in_code_block:
                # Closing fence
                result.append("{code}")
                in_code_block = False
            else:
                # Opening fence - extract optional language
                lang = line.strip()[3:].strip()
                if lang:
                    result.append(f"{{code:{lang}}}")
                else:
                    result.append("{code}")
                in_code_block = True
            continue

        if in_code_block:
            result.append(line)
            continue

        # Headers: # ## ### #### -> h1. h2. h3. h4.
        header_match = re.match(r"^(#{1,6})\s+(.+)$", line)
        if header_match:
            level = len(header_match.group(1))
            content = header_match.group(2).strip()
            # Convert inline formatting in headers too
            content = _md_inline_to_jira(content)
            result.append(f"h{level}. {content}")
            continue

        # Markdown table separator: |---|---|  -> skip entirely
        if re.match(r"^\|[\s\-:|]+\|$", line.strip()):
            continue

        # Markdown table rows
        if "|" in line and line.strip().startswith("|"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            cells = [_md_inline_to_jira(c) for c in cells]
            # Is this a header row? (no previous table row)
            is_header = len(result) == 0 or not result[-1].startswith("|")
            if is_header:
                result.append("||" + "||".join(cells) + "||")
            else:
                result.append("|" + "|".join(cells) + "|")
            continue

        # Horizontal rule: --- or *** or ___
        if re.match(r"^[\-\*_]{3,}\s*$", line.strip()):
            result.append("----")
            continue

        # Unordered list items: - item or * item -> * item (Jira uses *)
        list_match = re.match(r"^(\s*)[-*]\s+(.+)$", line)
        if list_match:
            indent = len(list_match.group(1))
            depth = (indent // 2) + 1
            content = _md_inline_to_jira(list_match.group(2))
            result.append("*" * depth + " " + content)
            continue

        # Ordered list items: 1. item -> # item
        ol_match = re.match(r"^(\s*)\d+\.\s+(.+)$", line)
        if ol_match:
            indent = len(ol_match.group(1))
            depth = (indent // 2) + 1
            content = _md_inline_to_jira(ol_match.group(2))
            result.append("#" * depth + " " + content)
            continue

        # Regular line: convert inline formatting
        result.append(_md_inline_to_jira(line))

    return "\n".join(result)


def _md_inline_to_jira(text: str) -> str:
    """Convert inline Markdown formatting to Jira wiki markup."""
    import re

    # Inline code: `code` -> {{code}}
    # Do this first before bold/italic to avoid conflicts
    text = re.sub(r"`([^`]+)`", r"{{\1}}", text)

    # Bold+italic: ***text*** or ___text___ -> *_text_*  (Jira)
    text = re.sub(r"\*{3}(.+?)\*{3}", r"*_\1_*", text)
    text = re.sub(r"_{3}(.+?)_{3}", r"*_\1_*", text)

    # Bold: **text** -> *text*
    text = re.sub(r"\*{2}(.+?)\*{2}", r"*\1*", text)

    # Strikethrough: ~~text~~ -> -text-
    text = re.sub(r"~~(.+?)~~", r"-\1-", text)

    # Links: [text](url) -> [text|url]
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"[\1|\2]", text)

    return text


def build_jira_detailed_comment(agent_result: AgentResult) -> str:
    output = agent_result.output.strip()

    # Convert Markdown to Jira wiki markup
    converted = markdown_to_jira_wiki(output)

    lines = [
        "h2. Agent execution details",
        "",
        "{panel:title=Coding agent output|borderStyle=solid|borderColor=#ccc"
        "|titleBGColor=#f4f5f7|bgColor=#ffffff}",
        "",
        converted,
        "",
        "{panel}",
    ]
    return "\n".join(lines)
