"""The Pipeline orchestrator.

Wires together an IssueTracker, a StoryRouter, a RepoHosting, and a
CodingAgent to implement the end-to-end "story to pull request" flow.

The orchestrator depends only on the abstract interfaces. Concrete
adapters are injected at construction time. This is what makes the
framework provider-agnostic.

Parallelism model:
- A ThreadPoolExecutor runs multiple stories in parallel.
- Each story acquires a per-repo lock before touching git. Stories
  on different repos run in parallel; stories on the same repo
  serialize.
- The polling loop is non-blocking with respect to workers: it keeps
  scanning the issue tracker while workers are busy.
- The polling loop filters out stories that are currently in-flight
  so they are not submitted twice before the tracker's label update
  becomes visible.
"""

from __future__ import annotations

import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from yokai.core.branch_naming import render_branch_name
from yokai.core.concurrency import (
    InFlightRegistry,
    RepoLockRegistry,
)
from yokai.core.exceptions import (
    AgentExecutionError,
    RepoHostingError,
    RoutingError,
    SpecPipelineError,
)
from yokai.core.formatters import (
    build_jira_detailed_comment,
    build_jira_short_comment,
    build_pr_description,
)
from yokai.core.hooks import HookRegistry
from yokai.core.interfaces import (
    CodingAgent,
    ExecutionStore,
    IssueTracker,
    NotificationSink,
    RepoHosting,
    StoryRouter,
)
from yokai.core.logging_setup import get_logger
from yokai.core.models import Story
from yokai.core.prompts import PromptBuilder, default_prompt_builder

log = get_logger("orchestrator")


@dataclass
class PipelineSettings:
    workspace_dir: Path
    branch_pattern: str = "feature/{issue_key}-ai-{timestamp}"
    poll_interval_seconds: int = 30
    max_parallel_stories: int = 4
    commit_message_template: str = (
        "feat({issue_key}): {title}\n\nGenerated by yokai"
    )
    pr_title_template: str = "[AI] {issue_key}: {title}"


class Pipeline:
    def __init__(
        self,
        *,
        tracker: IssueTracker,
        router: StoryRouter,
        hosting: RepoHosting,
        agent: CodingAgent,
        settings: PipelineSettings,
        prompt_builder: PromptBuilder | None = None,
        hooks: HookRegistry | None = None,
        notification_sinks: list[NotificationSink] | None = None,
        execution_store: ExecutionStore | None = None,
    ):
        self._tracker = tracker
        self._router = router
        self._hosting = hosting
        self._agent = agent
        self._settings = settings
        self._prompt_builder = prompt_builder or default_prompt_builder
        self._hooks = hooks or HookRegistry()
        self._sinks = list(notification_sinks or [])
        self._store = execution_store
        self._locks = RepoLockRegistry()
        self._in_flight = InFlightRegistry()

    def _emit(self, event: str, **payload) -> None:
        self._hooks.emit(event, payload)

    def _notify_started(self, story: Story, repo_slug: str) -> None:
        for sink in self._sinks:
            try:
                sink.notify_started(story, repo_slug)
            except Exception:
                log.exception(f"Notification sink failed on started for {story.key}")

    def _notify_succeeded(self, story, pr) -> None:
        for sink in self._sinks:
            try:
                sink.notify_succeeded(story, pr)
            except Exception:
                log.exception(f"Notification sink failed on succeeded for {story.key}")

    def _notify_failed(self, story: Story, error: str) -> None:
        for sink in self._sinks:
            try:
                sink.notify_failed(story, error)
            except Exception:
                log.exception(f"Notification sink failed on failed for {story.key}")

    def process_story(self, story: Story) -> None:
        """Process a single story end-to-end.

        This is the unit of work. It assumes the caller has already
        marked the story as in-flight and holds the per-repo lock.
        On any failure it notifies the tracker and re-raises.
        """
        log.info("=" * 60)
        log.info(f"PROCESSING: {story.key} - {story.title}")
        log.info("=" * 60)

        self._emit("before_process", story=story)
        self._tracker.mark_in_progress(story.key)

        try:
            repo_slug = self._router.resolve_repo(story)
            if not repo_slug:
                raise RoutingError(
                    f"No repository resolved for story {story.key}. "
                    f"Components={story.components} Labels={story.labels}"
                )
            log.info(f"Target repo: {repo_slug}")
            self._emit("after_resolve_repo", story=story, repo_slug=repo_slug)
            self._notify_started(story, repo_slug)

            repo = self._hosting.resolve_repo(repo_slug)
            repo_path = self._hosting.clone_or_update(
                repo, self._settings.workspace_dir
            )
            self._emit("after_clone", story=story, repo_path=repo_path)

            from yokai.core.models import Branch
            branch_name = render_branch_name(
                self._settings.branch_pattern,
                issue_key=story.key,
                title=story.title,
            )
            log.info(f"Creating branch: {branch_name}")
            self._hosting.create_branch(
                repo_path, Branch(name=branch_name, base=repo.default_branch)
            )

            prompt = self._prompt_builder(story)
            self._emit(
                "before_agent_run",
                story=story,
                repo_path=repo_path,
                prompt=prompt,
            )
            agent_result = self._agent.run(repo_path, prompt)
            log.info(f"Agent finished in {agent_result.duration_seconds:.1f}s")
            self._emit("after_agent_run", story=story, agent_result=agent_result)

            commit_message = self._settings.commit_message_template.format(
                issue_key=story.key, title=story.title
            )
            commit = self._hosting.commit_changes(repo_path, commit_message)
            if commit is None:
                self._tracker.add_comment(
                    story.key,
                    "Pipeline ran but the coding agent made no changes.",
                )
                if self._store is not None:
                    self._store.mark_failed(story.key, "no changes")
                return

            self._emit("after_commit", story=story, commit=commit)

            self._hosting.push_branch(repo_path, branch_name)
            self._emit("after_push", story=story, branch_name=branch_name)

            changed_files = self._hosting.get_changed_files(
                repo_path, repo.default_branch
            )

            pr_description = build_pr_description(
                story=story,
                story_url=self._tracker.get_story_url(story.key),
                branch_name=branch_name,
                target_branch=repo.default_branch,
                commit=commit,
                changed_files=changed_files,
            )
            pr_title = self._settings.pr_title_template.format(
                issue_key=story.key, title=story.title
            )
            pr = self._hosting.open_pull_request(
                repo=repo,
                source_branch=branch_name,
                target_branch=repo.default_branch,
                title=pr_title,
                description=pr_description,
            )
            self._emit("after_pull_request", story=story, pull_request=pr)

            short_comment = build_jira_short_comment(
                pr_url=pr.url,
                branch_name=branch_name,
                changed_files=changed_files,
            )
            self._tracker.add_comment(story.key, short_comment)

            detailed_comment = build_jira_detailed_comment(agent_result)
            self._tracker.add_comment(story.key, detailed_comment)

            if self._store is not None:
                self._store.mark_completed(story.key, pr.url)
            self._notify_succeeded(story, pr)
            self._emit("on_success", story=story, pull_request=pr)

            log.info(f"DONE: PR created for {story.key} at {pr.url}")

        except SpecPipelineError as e:
            log.error(f"Pipeline error processing {story.key}: {e}")
            self._tracker.mark_failed(story.key, str(e))
            if self._store is not None:
                self._store.mark_failed(story.key, str(e))
            self._notify_failed(story, str(e))
            self._emit("on_failure", story=story, error=e)
            raise
        except Exception as e:
            log.exception(f"Unexpected error processing {story.key}")
            err_msg = f"{type(e).__name__}: {e}"
            self._tracker.mark_failed(story.key, err_msg)
            if self._store is not None:
                self._store.mark_failed(story.key, err_msg)
            self._notify_failed(story, err_msg)
            self._emit("on_failure", story=story, error=e)
            raise

    def _process_story_safe(self, story: Story) -> None:
        """Wrapper run inside a worker thread: acquires repo lock, runs, cleans up."""
        try:
            repo_slug = self._router.resolve_repo(story)
            if not repo_slug:
                log.error(
                    f"Story {story.key} has no routable repo, unmarking"
                )
                self._in_flight.unmark(story.key)
                try:
                    self._tracker.mark_failed(
                        story.key, "No routable repository"
                    )
                except Exception:
                    log.exception("Failed to notify tracker of routing error")
                return

            lock = self._locks.get(repo_slug)
            log.info(
                f"Worker got {story.key} (repo {repo_slug}), waiting for lock"
            )
            with lock:
                log.info(f"Lock acquired for {repo_slug}, processing {story.key}")
                try:
                    self.process_story(story)
                except Exception:
                    log.exception(f"process_story failed for {story.key}")
        finally:
            self._in_flight.unmark(story.key)

    def run_once(self) -> int:
        """Poll the tracker once and submit all new stories to the pool.

        Returns the number of stories submitted. Does not wait for them
        to complete. This method is useful for tests and for cron-like
        modes where something else drives the polling loop.
        """
        stories = self._tracker.search_pending_stories()
        new_stories: list[Story] = []
        for story in stories:
            if self._in_flight.try_mark(story.key):
                new_stories.append(story)
            else:
                log.debug(f"Story {story.key} already in-flight, skipping")
        return len(new_stories)

    def run_forever(
        self, *, stop_condition: Callable[[], bool] | None = None
    ) -> None:
        """Run the polling loop indefinitely.

        Args:
            stop_condition: optional callable returning True to exit
                the loop gracefully. Useful for tests.
        """
        s = self._settings
        log.info(
            f"Pipeline starting: poll every {s.poll_interval_seconds}s, "
            f"max {s.max_parallel_stories} parallel"
        )

        executor = ThreadPoolExecutor(
            max_workers=s.max_parallel_stories,
            thread_name_prefix="story-worker",
        )

        try:
            while True:
                if stop_condition is not None and stop_condition():
                    log.info("Stop condition met, exiting")
                    return

                try:
                    stories = self._tracker.search_pending_stories()
                    new_stories: list[Story] = []
                    for story in stories:
                        if self._in_flight.try_mark(story.key):
                            new_stories.append(story)
                        else:
                            log.debug(
                                f"Story {story.key} already in-flight"
                            )

                    if new_stories:
                        log.info(
                            f"Found {len(new_stories)} new stories, "
                            f"submitting to pool"
                        )
                        for story in new_stories:
                            executor.submit(self._process_story_safe, story)
                except Exception:
                    log.exception("Error in polling loop")

                time.sleep(s.poll_interval_seconds)
        except KeyboardInterrupt:
            log.info("Stop requested, waiting for in-flight workers to finish")
        finally:
            executor.shutdown(wait=True)
            log.info("All workers terminated, exiting")
