"""Bridge to yokai.queue.Postprocessor.

Combines RepoHosting (for commit + push + PR) and IssueTracker (for
comments + final status) into a single Postprocessor that the
ResultHandler can invoke when a Worker completes a job successfully.

This is essentially the second half of the legacy Pipeline.process_story:
everything from `commit_changes` to the final Jira comments.

Idempotency note: if commit + push succeeds but PR creation or comment
fails, the next invocation by the ResultHandler will not retry (the
Postprocessor is invoked once per AGENT_COMPLETED job; on failure the
job goes to FAILED, not back to AGENT_COMPLETED). This is intentional:
recreating commits is dangerous. A failed postprocess requires manual
intervention via `yokai queue-retry <job-id>`.

Lifecycle hooks: the postprocessor accepts an optional HookRegistry
and emits the same events as the monolithic Pipeline does for the
second half of story processing: after_commit, after_push,
after_pull_request, on_success, on_failure. Plugins registered on the
HookRegistry receive these events with the same payload shape as the
legacy Pipeline, so they can be reused unchanged.
"""

from __future__ import annotations

from pathlib import Path

from yokai.core.formatters import (
    build_jira_detailed_comment,
    build_jira_short_comment,
    build_pr_description,
)
from yokai.core.hooks import HookRegistry
from yokai.core.interfaces import IssueTracker, RepoHosting
from yokai.core.logging_setup import get_logger
from yokai.core.models import AgentResult
from yokai.queue.models import Job, JobResult
from yokai.queue.postprocessor import PostprocessOutcome, Postprocessor
from yokai.queue_adapters.agent_runner import job_to_story

log = get_logger("queue_adapters.postprocessor")


class HostingTrackerPostprocessor(Postprocessor):
    def __init__(
            self,
            *,
            hosting: RepoHosting,
            tracker: IssueTracker,
            workspace_dir: str | Path,
            commit_message_template: str = (
                    "feat({issue_key}): {title}\n\nGenerated by yokai"
            ),
            pr_title_template: str = "[AI] {issue_key}: {title}",
            hooks: HookRegistry | None = None,
    ) -> None:
        self._hosting = hosting
        self._tracker = tracker
        self._workspace_dir = Path(workspace_dir).expanduser()
        self._commit_message_template = commit_message_template
        self._pr_title_template = pr_title_template
        self._hooks = hooks or HookRegistry()

    def _emit(self, event: str, **payload) -> None:
        """Safely emit a hook event. Never raises."""
        try:
            self._hooks.emit(event, payload)
        except Exception:
            log.exception(f"Hook {event} failed (non-fatal)")

    def run(self, job: Job, result: JobResult) -> PostprocessOutcome:
        if not result.success:
            return PostprocessOutcome(
                success=False,
                error="Postprocessor invoked on a non-success result",
            )
        if not result.branch_name:
            return PostprocessOutcome(
                success=False,
                error="JobResult has no branch_name; cannot postprocess",
            )

        story = job_to_story(job)
        try:
            repo = self._hosting.resolve_repo(job.repo_slug)
        except Exception as e:
            self._emit("on_failure", story=story, error=e)
            return PostprocessOutcome(
                success=False, error=f"resolve_repo failed: {e}"
            )

        # Re-derive the working tree path. The Worker prepared it via
        # HostingRepoCheckout in the same workspace_dir.
        # NOTE: this assumes worker and result handler share the same
        # workspace (single-host or shared FS deployment). For fully
        # decoupled hosts, a future adapter would re-clone from the
        # already-pushed branch.
        try:
            repo_path = self._hosting.clone_or_update(repo, self._workspace_dir)
        except Exception as e:
            self._emit("on_failure", story=story, error=e)
            return PostprocessOutcome(
                success=False, error=f"clone_or_update failed: {e}"
            )

        commit_message = self._commit_message_template.format(
            issue_key=story.key, title=story.title
        )
        try:
            commit = self._hosting.commit_changes(repo_path, commit_message)
        except Exception as e:
            self._emit("on_failure", story=story, error=e)
            return PostprocessOutcome(
                success=False, error=f"commit_changes failed: {e}"
            )

        if commit is None:
            try:
                self._tracker.add_comment(
                    story.key,
                    "Pipeline ran but the coding agent made no changes.",
                )
            except Exception:
                log.exception("Failed to comment on no-changes outcome")
            self._emit(
                "on_failure",
                story=story,
                error="Agent made no changes to commit",
            )
            return PostprocessOutcome(
                success=False, error="Agent made no changes to commit"
            )

        self._emit("after_commit", story=story, commit=commit)

        try:
            self._hosting.push_branch(repo_path, result.branch_name)
        except Exception as e:
            self._emit("on_failure", story=story, error=e)
            return PostprocessOutcome(
                success=False, error=f"push_branch failed: {e}"
            )

        self._emit(
            "after_push", story=story, branch_name=result.branch_name
        )

        try:
            changed_files = self._hosting.get_changed_files(
                repo_path, repo.default_branch
            )
        except Exception as e:
            log.warning(f"get_changed_files failed: {e}; continuing with []")
            changed_files = []

        try:
            story_url = self._tracker.get_story_url(story.key)
        except Exception:
            story_url = ""

        pr_description = build_pr_description(
            story=story,
            story_url=story_url,
            branch_name=result.branch_name,
            target_branch=repo.default_branch,
            commit=commit,
            changed_files=changed_files,
        )
        pr_title = self._pr_title_template.format(
            issue_key=story.key, title=story.title
        )

        try:
            pr = self._hosting.open_pull_request(
                repo=repo,
                source_branch=result.branch_name,
                target_branch=repo.default_branch,
                title=pr_title,
                description=pr_description,
            )
        except Exception as e:
            self._emit("on_failure", story=story, error=e)
            return PostprocessOutcome(
                success=False, error=f"open_pull_request failed: {e}"
            )

        self._emit("after_pull_request", story=story, pull_request=pr)

        # Comments on the tracker are best-effort: a failed comment
        # does not invalidate a successful PR.
        short_comment = build_jira_short_comment(
            pr_url=pr.url,
            branch_name=result.branch_name,
            changed_files=changed_files,
        )
        try:
            self._tracker.add_comment(story.key, short_comment)
        except Exception:
            log.exception(f"Failed to add short comment on {story.key}")

        # Synthesize an AgentResult so we can reuse the existing
        # detailed-comment formatter
        synthetic = AgentResult(
            success=True,
            output=result.agent_output,
            duration_seconds=result.duration_seconds,
        )
        detailed_comment = build_jira_detailed_comment(synthetic)
        try:
            self._tracker.add_comment(story.key, detailed_comment)
        except Exception:
            log.exception(f"Failed to add detailed comment on {story.key}")

        self._emit("on_success", story=story, pull_request=pr)
        return PostprocessOutcome(success=True, pr_url=pr.url)
