"""Bridge to yokai.queue.Postprocessor.

Combines RepoHosting and IssueTracker into a single Postprocessor that
the ResultHandler invokes when a Worker completes a job successfully.

Since 0.2.0a2 the Worker handles commit + push. The Postprocessor only
needs to: fetch the already-pushed branch, read changed files for the
PR description, open the PR, and comment on Jira.
"""

from __future__ import annotations

from pathlib import Path

from yokai.core.formatters import (
    build_jira_detailed_comment,
    build_jira_short_comment,
    build_pr_description,
)
from yokai.core.hooks import HookRegistry
from yokai.core.interfaces import IssueTracker, RepoHosting
from yokai.core.logging_setup import get_logger
from yokai.core.models import AgentResult, CommitInfo, RepoLocation
from yokai.queue.models import Job, JobResult
from yokai.queue.postprocessor import PostprocessOutcome, Postprocessor
from yokai.queue_adapters.agent_runner import job_to_story

log = get_logger("queue_adapters.postprocessor")


class HostingTrackerPostprocessor(Postprocessor):
    def __init__(
            self,
            *,
            hosting: RepoHosting,
            tracker: IssueTracker,
            workspace_dir: str | Path,
            commit_message_template: str = (
                    "feat({issue_key}): {title}\n\nGenerated by yokai"
            ),
            pr_title_template: str = "[AI] {issue_key}: {title}",
            hooks: HookRegistry | None = None,
    ) -> None:
        self._hosting = hosting
        self._tracker = tracker
        self._workspace_dir = Path(workspace_dir).expanduser()
        self._commit_message_template = commit_message_template
        self._pr_title_template = pr_title_template
        self._hooks = hooks or HookRegistry()

    def _emit(self, event: str, **payload) -> None:
        """Safely emit a hook event. Never raises."""
        try:
            self._hooks.emit(event, payload)
        except Exception:
            log.exception(f"Hook {event} failed (non-fatal)")

    def run(self, job: Job, result: JobResult) -> PostprocessOutcome:
        if not result.success:
            return PostprocessOutcome(
                success=False,
                error="Postprocessor invoked on a non-success result",
            )
        if not result.branch_name:
            return PostprocessOutcome(
                success=False,
                error="JobResult has no branch_name; cannot postprocess",
            )

        story = job_to_story(job)
        is_rework = job.payload.get("job_type") == "rework"

        try:
            repo = self._hosting.resolve_repo(job.repo_slug)
        except Exception as e:
            self._emit("on_failure", story=story, error=e)
            return PostprocessOutcome(
                success=False, error=f"resolve_repo failed: {e}"
            )

        if is_rework:
            return self._postprocess_rework(job, result, story)

        # The Worker already committed and pushed the branch. We only
        # need the repo_path to read changed files for the PR
        # description. We do a lightweight clone_or_update (which
        # fetches the already-pushed branch) and then checkout the
        # branch the worker pushed.
        try:
            repo_path = self._hosting.clone_or_update(repo, self._workspace_dir)
        except Exception as e:
            self._emit("on_failure", story=story, error=e)
            return PostprocessOutcome(
                success=False, error=f"clone_or_update failed: {e}"
            )

        # Checkout the branch the worker pushed so we can read the diff
        try:
            import subprocess
            subprocess.run(
                ["git", "checkout", result.branch_name],
                cwd=repo_path,
                capture_output=True,
                text=True,
                check=True,
            )
        except Exception:
            log.warning(
                f"Could not checkout {result.branch_name}, "
                f"continuing with changed_files from current HEAD"
            )

        try:
            changed_files = self._hosting.get_changed_files(
                repo_path, repo.default_branch
            )
        except Exception as e:
            log.warning(f"get_changed_files failed: {e}; continuing with []")
            changed_files = []

        try:
            story_url = self._tracker.get_story_url(story.key)
        except Exception:
            story_url = ""

        # Build a synthetic CommitInfo for the PR description from
        # whatever the worker committed
        try:
            import subprocess
            sha_result = subprocess.run(
                ["git", "rev-parse", "HEAD"],
                cwd=repo_path, capture_output=True, text=True,
            )
            sha = sha_result.stdout.strip() if sha_result.returncode == 0 else "unknown"
            short_sha = sha[:7]
        except Exception:
            sha, short_sha = "unknown", "unknown"

        commit = CommitInfo(
            sha=sha,
            short_sha=short_sha,
            message=f"feat({story.key}): {story.title}",
            files_changed=len(changed_files),
            insertions=sum(f.added for f in changed_files),
            deletions=sum(f.removed for f in changed_files),
        )

        pr_description = build_pr_description(
            story=story,
            story_url=story_url,
            branch_name=result.branch_name,
            target_branch=repo.default_branch,
            commit=commit,
            changed_files=changed_files,
        )
        pr_title = self._pr_title_template.format(
            issue_key=story.key, title=story.title
        )

        try:
            pr = self._hosting.open_pull_request(
                repo=repo,
                source_branch=result.branch_name,
                target_branch=repo.default_branch,
                title=pr_title,
                description=pr_description,
            )
        except Exception as e:
            self._emit("on_failure", story=story, error=e)
            return PostprocessOutcome(
                success=False, error=f"open_pull_request failed: {e}"
            )

        self._emit("after_pull_request", story=story, pull_request=pr)

        # Comments on the tracker are best-effort: a failed comment
        # does not invalidate a successful PR.
        short_comment = build_jira_short_comment(
            pr_url=pr.url,
            branch_name=result.branch_name,
            changed_files=changed_files,
        )
        try:
            self._tracker.add_comment(story.key, short_comment)
        except Exception:
            log.exception(f"Failed to add short comment on {story.key}")

        # Synthesize an AgentResult so we can reuse the existing
        # detailed-comment formatter
        synthetic = AgentResult(
            success=True,
            output=result.agent_output,
            duration_seconds=result.duration_seconds,
        )
        detailed_comment = build_jira_detailed_comment(synthetic)
        try:
            self._tracker.add_comment(story.key, detailed_comment)
        except Exception:
            log.exception(f"Failed to add detailed comment on {story.key}")

        self._emit("on_success", story=story, pull_request=pr)
        # Mark story as done: remove ai-processing, add ai-done
        try:
            self._tracker.mark_done(story.key)
        except Exception:
            log.exception(f"Failed to mark {story.key} as done (non-fatal)")
        return PostprocessOutcome(success=True, pr_url=pr.url)

    def _postprocess_rework(
            self,
            job: Job,
            result: JobResult,
            story,
    ) -> PostprocessOutcome:
        """Handle post-processing for rework jobs.

        No new PR is opened — the existing PR is already updated by
        the push. We resolve the addressed comments/tasks on the PR,
        comment on Jira, and update labels.
        """
        # Resolve comments and tasks on the PR
        pr_id = job.payload.get("pr_id", "")
        if pr_id:
            try:
                repo = self._hosting.resolve_repo(job.repo_slug)
                self._resolve_pr_feedback(repo, pr_id, job.payload)
            except Exception:
                log.exception(
                    f"Failed to resolve PR feedback for {story.key} (non-fatal)"
                )

        synthetic = AgentResult(
            success=True,
            output=result.agent_output,
            duration_seconds=result.duration_seconds,
        )
        rework_comment = build_jira_detailed_comment(synthetic)
        try:
            self._tracker.add_comment(
                story.key,
                f"h3. Rework completed\n\n{rework_comment}",
            )
        except Exception:
            log.exception(f"Failed to add rework comment on {story.key}")

        self._emit("on_success", story=story, pull_request=None)

        try:
            self._tracker.mark_rework_done(story.key)
        except Exception:
            log.exception(
                f"Failed to mark {story.key} as rework done (non-fatal)"
            )

        pr_url = job.payload.get("pr_url", "")
        return PostprocessOutcome(success=True, pr_url=pr_url)

    def _resolve_pr_feedback(
            self,
            repo: RepoLocation,
            pr_id: str,
            payload: dict,
    ) -> None:
        """Resolve all comments and complete all tasks that were in the rework."""
        pr_comments = payload.get("pr_comments", [])
        for comment in pr_comments:
            comment_id = comment.get("id", "")
            if not comment_id:
                continue
            text = comment.get("text", "")
            if text.startswith("[TASK]"):
                try:
                    self._hosting.complete_pr_task(repo, pr_id, comment_id)
                    log.info(f"Completed task {comment_id} on PR {pr_id}")
                except Exception:
                    log.warning(f"Failed to complete task {comment_id}")
            else:
                try:
                    self._hosting.resolve_pr_comment(repo, pr_id, comment_id)
                    log.info(f"Resolved comment {comment_id} on PR {pr_id}")
                except Exception:
                    log.warning(f"Failed to resolve comment {comment_id}")
